version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"  # Porta do seu servidor Express
      - "9229:9229"  # Porta do Debug (Nodemon)
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
